name: CI — Task Manager API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Verificar sintaxis del proyecto
        run: node --check src/app.js && node --check src/routes.js && node --check src/firebase.js